### ISSUE TITLE
网段识别问题

### ISSUE THREAD

**Issue by lintstar** [shmilylty/netspy#1]
师傅好~

测试发现 192.168.188.1 和 192.168.188.255 被识别成了两个网段

![image](https://user-images.githubusercontent.com/71202919/148005396-f56c608c-ba5c-4838-9015-f163fdeb89ba.png)

**Comment by shmilylty** [comment]
感谢 我修改一下

**Comment by kevinsnameneedlong** [comment]
cli.go源码里面只限定了1、2、254、255这几个，应该是指每个网段只探测这三个常见网关IP当存活判断基准。

**Comment by lintstar** [comment]
好勒 辛苦师傅了~ 

253 也出现了类似问题：

![image](https://user-images.githubusercontent.com/71202919/148054020-13ee136e-5a44-487c-9da6-68c2a5c8a448.png)


> 感谢 我修改一下
