### ISSUE TITLE
网段识别问题

### ISSUE THREAD

**Issue by liang960215** [shmilylty/netspy#3]
试别10网段时候发现只识别了10.254段，实际上10.100段也是可以ping通的
![1641441241](https://user-images.githubusercontent.com/44635826/148325765-088f2396-c6ee-4a73-8c7b-34634974c3d4.jpg)
![image](https://user-images.githubusercontent.com/44635826/148325856-a0059754-b580-441b-8113-5e861e1bddf2.png)

**Comment by shmilylty** [comment]
试一下`netspy.exe -n 10 ps -t 3`，增加ping次数。

**Comment by liang960215** [comment]
> 试一下`netspy.exe -n 10 ps -t 3`，增加ping次数。

试了下，还是不行，只能探测出10.254段，10.1段和10.100段没探测出来。
![image](https://user-images.githubusercontent.com/44635826/148335777-96efcd61-935b-4633-8140-82fe167aa079.png)
![image](https://user-images.githubusercontent.com/44635826/148335861-576b2472-95cb-4c94-9343-c6afb65ca6d6.png)

**Comment by owenie** [comment]
我的也遇到同样的问题，只能识别10.254.x.x

**Comment by shmilylty** [comment]
@owenie @liang960215 师傅们使用v0.0.3版本看看是否还存在这种情况

**Comment by owenie** [comment]
> @owenie @liang960215 师傅们使用v0.0.3版本看看是否还存在这种情况

我今天测了一下， 可以了

**Comment by liang960215** [comment]
> @owenie @liang960215 师傅们使用v0.0.3版本看看是否还存在这种情况

我也试了下，可以了，谢谢师傅。
