### ISSUE TITLE
加入参数切换网段存活检测与主机存活检测

### ISSUE THREAD

**Issue by timwhitez** [shmilylty/netspy#4]
比如检测指定段的全部主机存活情况

**Comment by shmilylty** [comment]
netspy定位就是做网段存活探测，不过现在支持指定网段探测了(-c参数)，以及段内随机IP末尾数字数量(-r参数)，那么使用这个两个参数可以变相实现需求(netspy -c 192.168.1.0/24 -r 255)。

**Comment by timwhitez** [comment]
老哥稳

**Comment by shmilylty** [comment]
现在v0.0.4版本已经支持 `netspy -f -c 192.168.1.0/24 -r 255 is`

**Comment by ShiverZm** [comment]
为啥不能指定探测某一台主机
