### ISSUE TITLE
希望添加代理模式

### ISSUE THREAD

**Issue by okoling** [shmilylty/netspy#5]
比如socks5模式探测

**Comment by shmilylty** [comment]
1.后续研究一下看一下能不能通过代理去探测
2.目前本地的话可以尝试使用proxychains或proxifier做一下代理

**Comment by okoling** [comment]
有尝试过用proxifier搭配tcp探测模式探测，效果不太理想，可能并发有点高了。

**Comment by shmilylty** [comment]
使用代理探测速度多多少少肯定会受影响
