### ISSUE TITLE
您好，扫描出来的子网掩码为什么全都是/24

### ISSUE THREAD

**Issue by 15536818056** [shmilylty/netspy#6]
172.31.26.99/24
172.31.237.254/24
172.31.28.209/24
172.31.246.254/24
172.31.224.2/24
172.31.190.255/24
172.31.107.126/24
172.31.87.179/24
172.31.125.227/24
172.31.148.98/24
172.31.209.255/24
172.31.203.255/24
172.31.243.2/24
172.31.255.2/24
172.31.210.255/24
172.31.181.255/24
172.31.89.114/24
10.0.0.2/24
172.31.213.255/24
172.31.172.219/24
172.31.225.255/24
172.31.222.255/24
172.31.192.95/24
172.31.242.255/24
172.31.205.14/24
172.31.252.255/24
172.31.245.255/24
10.3.15.255/24
10.3.0.255/24
10.3.27.255/24
10.3.16.255/24
10.10.24.1/24
10.10.68.1/24
10.10.80.1/24
10.10.108.1/24
10.10.104.1/24
10.10.128.1/24
10.10.136.1/24

**Comment by shmilylty** [comment]
探测出来的都是C段

**Comment by 15536818056** [comment]
哦，明白了，谢谢您
